// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuIhohKiNQ4qj_MuePQ1z2Guoz_ZSIkUk',
    appId: '1:1045066719761:web:879befe4d8fcba416587b0',
    messagingSenderId: '1045066719761',
    projectId: 'event-booking-app-ead70',
    authDomain: 'event-booking-app-ead70.firebaseapp.com',
    storageBucket: 'event-booking-app-ead70.firebasestorage.app',
    measurementId: 'G-CVFM3KFG3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-eMrjFD5e_qBElGl_Rmrum3way3hS-ZY',
    appId: '1:1045066719761:android:d1cb4c73a33acc256587b0',
    messagingSenderId: '1045066719761',
    projectId: 'event-booking-app-ead70',
    storageBucket: 'event-booking-app-ead70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB9I_FvK_o6tADrt33UxHH7gxcU7EyUT0',
    appId: '1:1045066719761:ios:9156ad1f7af5f12a6587b0',
    messagingSenderId: '1045066719761',
    projectId: 'event-booking-app-ead70',
    storageBucket: 'event-booking-app-ead70.firebasestorage.app',
    iosBundleId: 'com.example.sportsEventBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB9I_FvK_o6tADrt33UxHH7gxcU7EyUT0',
    appId: '1:1045066719761:ios:9156ad1f7af5f12a6587b0',
    messagingSenderId: '1045066719761',
    projectId: 'event-booking-app-ead70',
    storageBucket: 'event-booking-app-ead70.firebasestorage.app',
    iosBundleId: 'com.example.sportsEventBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuIhohKiNQ4qj_MuePQ1z2Guoz_ZSIkUk',
    appId: '1:1045066719761:web:d29c056d82bd6b8a6587b0',
    messagingSenderId: '1045066719761',
    projectId: 'event-booking-app-ead70',
    authDomain: 'event-booking-app-ead70.firebaseapp.com',
    storageBucket: 'event-booking-app-ead70.firebasestorage.app',
    measurementId: 'G-XHZHYQFMZD',
  );

}